name = "PyFenicsAD"
uuid = "5b1844ce-4078-4f5c-bcff-d734502dd105"
authors = ["Ivan Yashchuk <ivan.yashchuk@aalto.fi>"]
version = "0.1.0"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
